"""add case totals and inconsistency flags

Revision ID: 335e801047b2
Revises: dcafec68611f
Create Date: 2026-09-14 16:46:58.890096

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '335e801047b2'
down_revision: str | Sequence[str] | None = 'dcafec68611f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_totals',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('total_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_wages', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('inconsistency_flags',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inconsistency_flags')
    op.drop_table('case_totals')
    # ### end Alembic commands ###
